import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by '135480' at '2/7/17 3:02 PM' with Gradle 3.1
 *
 * @author 135480, @date 2/7/17 3:02 PM
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
    
    @Test public void testSomeLibraryMethod2() {
        Library classUnderTest = new Library();
        assertEquals("getFileName should return 'sample.wav'", classUnderTest.getFileName());
    }    
    
    @Test public void testSomeLibraryMethod3() {
        Library classUnderTest = new Library();
        assertEquals("getSiteName should return 'http://s2t2t.mybluemix.net'", classUnderTest.getSiteName());
    }      
}
